version: "3.8"

services:
  # PostgreSQL 서비스
  db:
    image: postgres:14-alpine # PostgreSQL 공식 이미지 사용
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432" # PostgreSQL의 기본 포트
