name: Build Docker Image

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 트리거
  workflow_dispatch:

jobs:
  build:
    runs-on: shlee # Self-hosted Runner에서 실행
    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Docker 이미지 빌드
      - name: Build Docker Image
        run: |
          docker build -t snms-web99 .
